"""Add new table

Revision ID: 9e878b7bb589
Revises: 52777784259c
Create Date: 2025-10-30 16:10:48.541740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e878b7bb589'
down_revision: Union[str, Sequence[str], None] = '52777784259c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postbase',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_source', sa.String(length=16000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_postbase_user_id'), 'postbase', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postbase_user_id'), table_name='postbase')
    op.drop_table('postbase')
    # ### end Alembic commands ###
