"""Add post table

Revision ID: d29a5cd664c9
Revises: beecc603d730
Create Date: 2025-10-31 11:28:02.200607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29a5cd664c9'
down_revision: Union[str, Sequence[str], None] = 'beecc603d730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('time_to_publish', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'time_to_publish')
    # ### end Alembic commands ###
