"""Add new row

Revision ID: ebad6bdad92c
Revises: 26e9acc2e3cb
Create Date: 2025-10-30 12:34:19.381579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebad6bdad92c'
down_revision: Union[str, Sequence[str], None] = '26e9acc2e3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikibase',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_source', sa.String(length=16000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_wikibase_user_id'), 'wikibase', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wikibase_user_id'), table_name='wikibase')
    op.drop_table('wikibase')
    # ### end Alembic commands ###
